version: 2
updates:
  - package-ecosystem: docker
    directory: "/pgbouncer"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/pgbouncer"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/proxy"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/redis"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/eth_worker"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/app"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/app"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/eth_worker"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/app"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
