version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: "server:${IMAGE_TAG:-latest}"
    environment:
      CONTAINER_TYPE: "APP"
    depends_on:
      - postgres
      - eth_worker
    ports:
      - "3031:3031"
      - "9000:9000"

  eth_worker:
    build:
      context: .
      dockerfile: eth_worker/Dockerfile
    image: "eth_worker:${IMAGE_TAG:-latest}"
    environment:
      CONTAINER_TYPE: "PRIMARY"
      PYTHONUNBUFFERED: 0
      CI: "false"
    depends_on:
      - redis
      - ganache
      - eth_postgres

  pgbouncer:
    build:
      context: .
      dockerfile: pgbouncer/Dockerfile
    image: "pgbouncer:${IMAGE_TAG:-latest}"

  proxy:
    build: proxy
    image: "proxy:${IMAGE_TAG:-latest}"
    ports:
      - "80:80"
    depends_on:
      - app

  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: "sempo_docker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  eth_postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: "sempo_docker_eth"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  redis:
    image: "redis:alpine"

  ganache:
    image: "trufflesuite/ganache-cli:v6.7.0"
    command: "-l 80000000 -i 42"